
@startuml
'https://plantuml.com/class-diagram

abstract class Wrapper<T> implements ISqlSegment
abstract class AbstractWrapper extends Wrapper  implements Compare, Nested, Join, Func

class QueryWrapper extends AbstractWrapper  implements Query
class EmptyWrapper<T> extends QueryWrapper

class UpdateWrapper extends AbstractWrapper  implements Update
abstract class AbstractLambdaWrapper extends AbstractWrapper

class LambdaQueryWrapper extends AbstractLambdaWrapper  implements Query
class LambdaUpdateWrapper extends AbstractLambdaWrapper  implements Update


@enduml