@startuml
'https://plantuml.com/class-diagram

interface IService

class ServiceImpl implements IService{
    @Autowired
    # M baseMapper;
    # Class<T> entityClass;
    # Class<M> mapperClass;
}



@enduml